# Generated by Django 4.0.1 on 2022-12-01 01:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='neptunuser',
            name='uploaded_calendar',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
